[package]
name = "async-signals"
version = "0.2.0"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Library for easier and safe Unix signal handling, and async!"
repository = "https://github.com/Sherlock-Holo/async-signal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = { version = "0.1", features = ["mio-support"] }
mio = "0.6"
lazy_static = "1.4"
futures-util = "0.3"
libc = "0.2"

[dev-dependencies]
async-std = { version = "1.5", features = ["attributes"] }
nix = "0.17"
